"""add_qa_fields_to_article

Revision ID: 1f708865c4d8
Revises: 429e7079f22b
Create Date: 2026-05-22 14:52:47.234246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1f708865c4d8'
down_revision: Union[str, None] = '429e7079f22b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('qa_status', sa.String(length=50), nullable=True))
    op.add_column('articles', sa.Column('qa_results', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'qa_results')
    op.drop_column('articles', 'qa_status')
    # ### end Alembic commands ###
