"""Initial database schema with string IDs

Revision ID: cbaf70949320
Revises: 
Create Date: 2026-01-08 19:50:30.108612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbaf70949320'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('api_calls_today', sa.Integer(), nullable=False),
    sa.Column('api_calls_month', sa.Integer(), nullable=False),
    sa.Column('last_api_call', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_expires', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('target_country', sa.String(length=5), nullable=False),
    sa.Column('primary_keywords', sa.JSON(), nullable=False),
    sa.Column('secondary_keywords', sa.JSON(), nullable=False),
    sa.Column('competitor_urls', sa.JSON(), nullable=False),
    sa.Column('content_strategy', sa.JSON(), nullable=False),
    sa.Column('total_articles', sa.Integer(), nullable=False),
    sa.Column('published_articles', sa.Integer(), nullable=False),
    sa.Column('draft_articles', sa.Integer(), nullable=False),
    sa.Column('avg_word_count', sa.Integer(), nullable=False),
    sa.Column('total_search_volume', sa.Integer(), nullable=False),
    sa.Column('estimated_traffic', sa.Integer(), nullable=False),
    sa.Column('writing_style', sa.JSON(), nullable=False),
    sa.Column('seo_settings', sa.JSON(), nullable=False),
    sa.Column('ai_settings', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED', name='articlestatus'), nullable=False),
    sa.Column('article_type', sa.Enum('BLOG_POST', 'PRODUCT_PAGE', 'LANDING_PAGE', 'FAQ', 'GUIDE', 'NEWS', name='articletype'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('meta_keywords', sa.JSON(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('reading_time', sa.Integer(), nullable=False),
    sa.Column('primary_keyword', sa.String(length=200), nullable=True),
    sa.Column('secondary_keywords', sa.JSON(), nullable=False),
    sa.Column('keyword_density', sa.Float(), nullable=False),
    sa.Column('seo_score', sa.Float(), nullable=False),
    sa.Column('readability_score', sa.Float(), nullable=False),
    sa.Column('headings', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('generation_settings', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wordpress_id', sa.String(length=50), nullable=True),
    sa.Column('external_url', sa.String(length=1000), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('avg_ranking', sa.Float(), nullable=True),
    sa.Column('search_impressions', sa.Integer(), nullable=False),
    sa.Column('search_clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_articles_primary_keyword'), 'articles', ['primary_keyword'], unique=False)
    op.create_index(op.f('ix_articles_project_id'), 'articles', ['project_id'], unique=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=False)
    op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.create_index(op.f('ix_articles_user_id'), 'articles', ['user_id'], unique=False)
    op.create_table('search_caches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('search_type', sa.String(length=50), nullable=False),
    sa.Column('num_results', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('total_results', sa.Integer(), nullable=False),
    sa.Column('search_time', sa.Float(), nullable=False),
    sa.Column('serp_features', sa.JSON(), nullable=False),
    sa.Column('organic_results', sa.JSON(), nullable=False),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('competition_level', sa.String(length=20), nullable=True),
    sa.Column('competition_index', sa.Float(), nullable=True),
    sa.Column('cpc_low', sa.Float(), nullable=True),
    sa.Column('cpc_high', sa.Float(), nullable=True),
    sa.Column('analyzed', sa.Boolean(), nullable=False),
    sa.Column('analysis_data', sa.JSON(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_cache_expires', 'search_caches', ['expires_at'], unique=False)
    op.create_index('idx_search_cache_query_lang_country', 'search_caches', ['query', 'language', 'country'], unique=False)
    op.create_index('idx_search_cache_user_project', 'search_caches', ['user_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_search_caches_cache_key'), 'search_caches', ['cache_key'], unique=True)
    op.create_index(op.f('ix_search_caches_expires_at'), 'search_caches', ['expires_at'], unique=False)
    op.create_index(op.f('ix_search_caches_id'), 'search_caches', ['id'], unique=False)
    op.create_index(op.f('ix_search_caches_project_id'), 'search_caches', ['project_id'], unique=False)
    op.create_index(op.f('ix_search_caches_query'), 'search_caches', ['query'], unique=False)
    op.create_index(op.f('ix_search_caches_search_type'), 'search_caches', ['search_type'], unique=False)
    op.create_index(op.f('ix_search_caches_user_id'), 'search_caches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_caches_user_id'), table_name='search_caches')
    op.drop_index(op.f('ix_search_caches_search_type'), table_name='search_caches')
    op.drop_index(op.f('ix_search_caches_query'), table_name='search_caches')
    op.drop_index(op.f('ix_search_caches_project_id'), table_name='search_caches')
    op.drop_index(op.f('ix_search_caches_id'), table_name='search_caches')
    op.drop_index(op.f('ix_search_caches_expires_at'), table_name='search_caches')
    op.drop_index(op.f('ix_search_caches_cache_key'), table_name='search_caches')
    op.drop_index('idx_search_cache_user_project', table_name='search_caches')
    op.drop_index('idx_search_cache_query_lang_country', table_name='search_caches')
    op.drop_index('idx_search_cache_expires', table_name='search_caches')
    op.drop_table('search_caches')
    op.drop_index(op.f('ix_articles_user_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_index(op.f('ix_articles_project_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_primary_keyword'), table_name='articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
